name: Build and Release Electron App

on:
  push:
    branches:
      - main
      - release
      - feature/add-github-actions-workflow

permissions:
  contents: write

jobs:
  mac-linux-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - os: macos
            platform: darwin
          - os: ubuntu
            platform: linux

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      # ここにテストが入る

      - name: Package Electron app
        run: npm run make -- --platform ${{ matrix.platform }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-build
          path: out/make/${{ matrix.platform }}

  windows-build:
    runs-on: windows-2019

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      # ここにテストが入る

      - name: Package Electron app
        run: npm run make -- --platform win32

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: out/make/win32

  upload-to-google-drive:
    needs:
      - mac-linux-build
      - windows-build

    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Upload to Google Drive
        uses: satackey/action-google-drive@v1
        with:
          skicka-tokencache-json: ${{ secrets.SKICKA_TOKENCACHE_JSON }}
          upload-from: .
          upload-to: /manakan
          overwrite: true
          google-client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
          google-client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
