name: Build and Release Electron App

on:
  push:
    branches:
      - main
      - release
      - feature/add-github-actions-workflow

jobs:
  mac-linux-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - os: macos
            platform: darwin
          - os: ubuntu
            platform: linux

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      # ここにテストが入る

      - name: Package Electron app
        run: npm run make -- --platform ${{ matrix.platform }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-build
          path: |
            out/make/**/*

      - name: Update Wiki with artifact URL
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const artifactUrl = '${{ steps.upload-artifact.outputs.artifact-url }}';
            const wikiPage = 'Artifact-URLs.md';
            let wikiContent = '';

            try {
              const { data } = await github.rest.repos.getContent({
                owner: context.repo.owner,
                repo: context.repo.repo,
                path: wikiPage,
              });
              wikiContent = Buffer.from(data.content, 'base64').toString();
            } catch (error) {
              if (error.status !== 404) {
                throw error;
              }
            }

            const platform = '${{ matrix.platform }}';
            const regex = new RegExp(`\\[${platform}\\]\\(.*\\)`, 'gm');
            const newLine = `[${platform}](${artifactUrl})`;

            if (regex.test(wikiContent)) {
              wikiContent = wikiContent.replace(regex, newLine);
            } else {
              wikiContent += `\n${newLine}`;
            }

            await github.rest.repos.createOrUpdateFileContents({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: wikiPage,
              message: 'Update artifact URLs in wiki',
              content: Buffer.from(wikiContent).toString('base64'),
              sha: data ? data.sha : undefined,
            });

  windows-build:
    runs-on: windows-2019

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      # ここにテストが入る

      - name: Package Electron app
        run: npm run make -- --platform win32

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            out/make/**/*

      - name: Update Wiki with artifact URL
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const artifactUrl = '${{ steps.upload-artifact.outputs.artifact-url }}';
            const wikiPage = 'Artifact-URLs.md';
            let wikiContent = '';

            try {
              const { data } = await github.rest.repos.getContent({
                owner: context.repo.owner,
                repo: context.repo.repo,
                path: wikiPage,
              });
              wikiContent = Buffer.from(data.content, 'base64').toString();
            } catch (error) {
              if (error.status !== 404) {
                throw error;
              }
            }

            const platform = 'windows';
            const regex = new RegExp(`\\[${platform}\\]\\(.*\\)`, 'gm');
            const newLine = `[${platform}](${artifactUrl})`;

            if (regex.test(wikiContent)) {
              wikiContent = wikiContent.replace(regex, newLine);
            } else {
              wikiContent += `\n${newLine}`;
            }

            await github.rest.repos.createOrUpdateFileContents({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: wikiPage,
              message: 'Update artifact URLs in wiki',
              content: Buffer.from(wikiContent).toString('base64'),
              sha: data ? data.sha : undefined,
            });
