name: Build and Release Electron App

on:
  push:
    branches:
      - main
      - release
      - feature/add-github-actions-workflow

permissions:
  contents: write

jobs:
  mac-linux-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - os: macos
            platform: darwin
          - os: ubuntu
            platform: linux

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      # ここにテストが入る

      - name: Package Electron app
        run: npm run make -- --platform ${{ matrix.platform }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-build
          path: |
            out/make/**/*

    outputs:
      artifact_name: ${{ matrix.platform }}-build

  windows-build:
    runs-on: windows-2019

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      # ここにテストが入る

      - name: Package Electron app
        run: npm run make -- --platform win32

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            out/make/**/*

    outputs:
      artifact_name: windows-build

  update-wiki:
    needs:
      - mac-linux-build
      - windows-build

    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Check out wiki repo
        uses: actions/checkout@v4
        with:
          repository: "${{ github.repository }}.wiki"
          path: .wiki

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Update wiki pages
        run: |
          echo -e "# Artifact URLs\n\n" > .wiki/artifact-urls.md

          for platform in darwin linux windows; do
            artifact_name="${{ needs.mac-linux-build.outputs.artifact_name }}"
            if [ "$platform" == "windows" ]; then
              artifact_name="${{ needs.windows-build.outputs.artifact_name }}"
            fi

            echo -e "## $platform\n\n" >> .wiki/artifact-urls.md
            for file in artifacts/$artifact_name/*; do
              filename=$(basename "$file")
              cp -r "$file" ".wiki/$filename"
              echo -e "[$filename]($filename)\n\n" >> .wiki/artifact-urls.md
            done
          done

      - name: Stage and count changes
        working-directory: .wiki
        id: staging
        run: |
          git add .
          echo "NUM_OF_STAGED=$(git diff --staged --name-only | wc -l)" >> $GITHUB_OUTPUT

      - name: Commit wiki pages
        working-directory: .wiki
        if: steps.staging.outputs.NUM_OF_STAGED > 0
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git commit -m "${GITHUB_WORKFLOW}"
          git push
